import { useState, useEffect } from "react";
import { twMerge } from "tailwind-merge";
import { SvgLoader, Card, FormField } from "../components";

const RenderCards = ({ data, message }) => {
  // If data exists then render data over the Card component.
  if (data?.length > 0)
    return data.map((post) => <Card key={post.id} {...post} />);

  // If no data exist
  return (
    <h2
      className={twMerge("text-xl font-bold uppercase text-[#6469ff]", "mt-5")}
    >
      {message}
    </h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearhText] = useState("");

  return (
    <section
      className={twMerge(
        "mx-auto",
        "max-w-7xl", // max-width: 80rem = 1280px
      )}
    >
      {/* Title */}
      <div>
        <h1 className="text-[32px] font-extrabold text-[#222328]">
          The Community Showcase
        </h1>
        <p
          className={twMerge(
            "text-[16px] text-[#666e75]",
            "mt-2 max-w-[500px]",
          )}
        >
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI.
        </p>
      </div>

      {/* Form Field */}
      <div className="mt-16">
        <FormField />
      </div>

      {/* Results */}
      <div className="mt-10">
        {loading ? (
          // Loader
          <div className="flex items-center justify-center">
            <SvgLoader />
          </div>
        ) : (
          // Results
          <>
            {searchText && (
              <h2
                className={twMerge(
                  "text-xl font-medium text-[#666e75]",
                  "mb-3",
                )}
              >
                Showing results for{" "}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}

            <div
              className={twMerge(
                "grid grid-cols-1 xs:grid-cols-2 sm:grid-cols-3 lg:grid-cols-4",
                "gap-3",
              )}
            >
              {searchText ? (
                <RenderCards data={[]} message="No search results found" />
              ) : (
                <RenderCards data={[]} message="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
